application: qr-tools
version: prod
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /scripts
  static_dir: scripts

- url: /stylesheets
  static_dir: stylesheets
  
- url: /img
  static_dir: img
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
